apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.fullName }}
  labels:
    uninstall: {{ .Values.selectorLabel }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.selectorLabel }}
    spec:
      containers:
        - name:  {{ .Values.containers.server.name}}
          image:  {{ .Values.containers.server.image}}
          ports:
            - containerPort: {{ .Values.containers.server.httpPort}}
          env:
            - name: "serverHost"
              value: {{ .Values.containers.server.httpHost}}
            - name: "serverPort"
              value: "{{ .Values.containers.server.httpPort}}"
            - name: "baseDir"
              value: "{{ .Values.containers.server.baseDir}}"
