apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    uninstall: {{ .Values.selectorLabel }}
spec:
  rules:
    - host: get.alexstorm.solenopsys.org
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name:  {{ .Values.fullName }}
                port:
                  number: {{ .Values.service.httpPort }}