apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hc-infra-list-pods
subjects:
  - kind: ServiceAccount
    name: hc-infra
    namespace: default
roleRef:
  kind: ClusterRole
  name: list-pods
  apiGroup: rbac.authorization.k8s.io