apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-configmaps
rules:
  - apiGroups:
      - "*"
    resources: [ configmaps, leases, helmcharts ]
    verbs: [ get, update, create ]